language: python
python:
  - "3.2"
env:
 - TOXENV=py32
virtualenv:
  system_site_packages: true
before_install:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
install:
 # install deps
 - sudo apt-get install -qq python3-pyqt4 --fix-missing
 - pip install tox
script:
 - tox
